#!/bin/bash

# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>. For any questions
# about this software or licensing, please email opensource@seagate.com or
# cortx-questions@seagate.com.

set -eu -o pipefail

HA_PATH="<HA_PATH>"

LOCAL_NODE_MINION_ID=$(salt-call grains.get id --output=json | jq '.["local"]' | sed s/\"//g)

remove_node() {
    # Get node name for replace node
    faulty_node=$( get_faulty_node )

    cortxha cluster remove_node $faulty_node || {
        echo "Failed to remove $faulty_node node to cluster"
        exit 1
    }

    exit 0
}

add_node() {
    # Get node name for replace node
    faulty_node=$( get_faulty_node )

    cortxha cluster add_node $faulty_node || {
        echo "Failed to add $faulty_node node to cluster"
        exit 1
    }

    exit 0
}

# Helping function
get_faulty_node(){
    # Get node name for replace node
    node_list=$(salt-call --local pillar.get cluster:node_list --output=json)
    host1=$(echo $node_list | jq '.["local"][0]' | sed s/\"//g)
    host2=$(echo $node_list | jq '.["local"][1]' | sed s/\"//g)

    # Get Faluty node name
    if [[ $LOCAL_NODE_MINION_ID == $host1 ]]; then
        faulty_node=$host2
    else
        faulty_node=$host1
    fi
    echo $faulty_node
}

ACTION=$1

$ACTION
