#!/bin/bash

HA_PATH="<HA_PATH>"

post_install() {
    echo "post_install"
    mkdir -p /etc/logrotate.d/
    cp -rf ${HA_PATH}/conf/logrotate/cortx_ha_log.conf /etc/logrotate.d/
}

init() {
    echo "init"
}

config() {
    echo "config"
}

test() {
    echo "test"
}

reset() {
    echo "reset"
}

ACTION=$1
# Call action
$ACTION
